### ISSUE TITLE
Autocomplete doesn't fully override

### ISSUE THREAD

**Issue by akurtakov** [redhat-developer/eclipseide-jdtls#46]
Let's make sure issue is not already fixed in snapshots first.

- [x] I verified I can reproduce this issue against latest [snapshots build](https://github.com/redhat-developer/eclipseide-jdtls#-installation)

## Steps to reproduce

From a fresh installation and clean workspace:

[Screencast from 2023-04-04 18-08-57.webm](https://user-images.githubusercontent.com/574788/229837063-4062ed77-dee0-46a6-b722-80e64416c397.webm) shows using *sysout* template and how a leading 's' symbol stays making the code illegal.

## Tested under this environment:
* OS & version: Fedora 38
* Eclipse IDE/Platform version: Eclipse 4.28 I-build

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by akurtakov** [comment]
@rgrunber is there anything special done for templates e.g. sysout in vscode-java ? What is https://github.com/redhat-developer/vscode-java/blob/master/snippets/server.json#L2 for ?

**Comment by rgrunber** [comment]
I would guess that things like https://github.com/redhat-developer/vscode-java/blob/master/snippets/server.json are used at https://github.com/redhat-developer/vscode-java/blob/d0f4f5bbb80b44ebbc4407f23e4a976bc7477a05/src/snippetCompletionProvider.ts#L12 as a temporary measure until the LS is up, since the same snippets are available at https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/CodeSnippetTemplate.java . See https://github.com/redhat-developer/vscode-java/blob/d0f4f5bbb80b44ebbc4407f23e4a976bc7477a05/src/standardLanguageClient.ts#L147-L148 .

**Comment by mickaelistria** [comment]
This is https://github.com/eclipse/eclipse.jdt.ls/issues/2626

**Comment by mickaelistria** [comment]
https://github.com/redhat-developer/eclipseide-jdtls/pull/63 adds a test to cover that case.

**Comment by mickaelistria** [comment]
#63 is merged and validates upstream fix in the LS works.
